import { useState, useEffect } from 'react'
import { parseFrontmatter, normalizeLang } from '../lib/frontmatter'

/**
 * Markdown-based CMS hooks.
 *
 * Content lives in `public/posts/<section>/` and is fetched at runtime, so it
 * can be edited without touching React code. Every file is `<base>-<lang>.md`,
 * where only the `-pt.md` is hand-written — the `-en.md` is generated by
 * `scripts/translate.mjs`.
 *
 * Parsing is delegated to `src/lib/frontmatter.js`, which the translator also
 * uses, so both ends of the pipeline agree on the format.
 */

const DEFAULT_LANG = 'pt'

/**
 * Build the ordered fallback list for a content file: the requested language
 * first, then Portuguese, then the language-less name. Partial translations
 * therefore degrade to PT instead of rendering an empty section.
 */
function candidatesFor(base, lang) {
  const normalized = normalizeLang(lang)
  const names = [`${base}-${normalized}.md`, `${base}-${DEFAULT_LANG}.md`, `${base}.md`]
  return [...new Set(names)]
}

/**
 * Fetch the first candidate that exists, parsed. Returns null if none do.
 * Aborts propagate to the caller so stale responses can be discarded.
 */
async function fetchFirstAvailable(section, candidates, signal) {
  for (const filename of candidates) {
    const response = await fetch(`/posts/${section}/${filename}`, { signal })
    if (response.ok) {
      return parseFrontmatter(await response.text())
    }
  }
  return null
}

/**
 * useContent Hook
 *
 * Loads a single content file, transparently falling back across languages.
 *
 * Example:
 *   const { content } = useContent('about', 'main', i18n.language)
 *   // tries /posts/about/main-en.md → main-pt.md → main.md
 *
 * @param {string} section - Section folder name (e.g. 'about', 'contact')
 * @param {string} base - File base name, without the language suffix
 * @param {string} [lang='pt'] - Language code ('pt' | 'en' | 'pt-BR' | …)
 * @returns {{content: Object|null, isLoading: boolean, error: Error|null}}
 */
export function useContent(section, base, lang = DEFAULT_LANG) {
  const [content, setContent] = useState(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    const controller = new AbortController()

    const load = async () => {
      setIsLoading(true)
      setError(null)

      try {
        const parsed = await fetchFirstAvailable(
          section,
          candidatesFor(base, lang),
          controller.signal,
        )
        setContent(parsed)
      } catch (err) {
        // A superseded request (language switched mid-flight) is not an error.
        if (err.name === 'AbortError') return
        console.error(`Failed to load ${section}/${base}:`, err)
        setError(err)
        setContent(null)
      } finally {
        if (!controller.signal.aborted) setIsLoading(false)
      }
    }

    load()
    return () => controller.abort()
  }, [section, base, lang])

  return { content, isLoading, error }
}

/**
 * useContentList Hook
 *
 * Loads every file listed in a section's `index.json`, in order.
 *
 * Index format:
 *   { "files": ["event-1", "event-2"] }    // base names, no language suffix
 *   { "files": ["event-1.md"] }            // legacy format, also accepted
 *
 * @param {string} section - Section folder name
 * @param {string} [lang='pt'] - Language code
 * @returns {{items: Array, isLoading: boolean, error: Error|null}}
 */
export function useContentList(section, lang = DEFAULT_LANG) {
  const [items, setItems] = useState([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState(null)

  useEffect(() => {
    const controller = new AbortController()

    const load = async () => {
      setIsLoading(true)
      setError(null)

      try {
        const indexResponse = await fetch(`/posts/${section}/index.json`, {
          signal: controller.signal,
        })

        if (!indexResponse.ok) {
          setItems([])
          return
        }

        const index = await indexResponse.json()
        const files = Array.isArray(index?.files) ? index.files : []

        const loaded = await Promise.all(
          files.map((entry) => {
            // Strip `.md` and any language suffix from legacy index entries.
            const base = entry.replace(/\.md$/, '').replace(/-(pt|en)$/, '')
            return fetchFirstAvailable(
              section,
              candidatesFor(base, lang),
              controller.signal,
            )
          }),
        )

        setItems(loaded.filter(Boolean))
      } catch (err) {
        if (err.name === 'AbortError') return
        console.error(`Failed to load section ${section}:`, err)
        setError(err)
        setItems([])
      } finally {
        if (!controller.signal.aborted) setIsLoading(false)
      }
    }

    load()
    return () => controller.abort()
  }, [section, lang])

  return { items, isLoading, error }
}

export default useContent
